name: CML AMP Text-generation-webui
description: |
  WebUI base text generation in the CML platform.

author: Sangjunni
specification_version: 1.0
prototype_version: 1.0
date: "2024-04-19"

environment_variables:
  PYTHONPATH:
    default: "/home/cdsw/.local/lib/python3.10/site-packages"
    description: "Leave this value as is. This is required by CML due to cml-addons module overriding user installed modules."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: download_requirements.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 16
    memory: 128
    gpu: 2
    
  - type: start_application
    bypass_authentication : true
    name: Stable Diffusion Text to Image
    subdomain: CML-text-generation-webui
    script: start_app.py
    short_summary: Create and start CML Text Generation WebUI application
    long_summary: Create and start CML ext Generation WebUI application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 16
    memory: 128
    gpu: 2
    environment_variables:
      TASK_TYPE: START_APPLICATION